apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mssql
  namespace: prod-tour-of-heroes
spec:
  encryptedData:
    SA_PASSWORD: AgAJG7k1YXvw4dZQEeFZdblggTdY3L7L+MK7YUoq6QTHzDK1z7CL9JlJYUexcV4kLrt76rfRRrgpJxYpaE2hMr/waUqTyfElKcRMiuuZkLpVaBIj33KdCOHO4/3HO86tV6mXO0HM4L9R0/7dEK47O2L277xsw9xf5xBiZVJMJ/kQMcH+Uqr3rlniyrTvY1p5dID6WiG2sSBgTQWWK6CaI/m7wSSHxIgXSewfoF3HDFuSGXG3/+eMbS4J+SU9UEOJWqvsGyLhyWuYEuJnCYQ0hDFFTp+yFavktBtt49vv2nRbpgNdoge7nszJr6oWv28DlnDOlpQe7ZhOpaId4cEhkMHNiUofBQafPunsajmxVndcduSu1UYuFVZMVfgHDlR41Cr1ke+5ku3BavIiiqLocr7I7EQ46gf2WCfmCvUwxK9rYDi1aNaljsrwhA5O3k6GaM+M4fEc5HqzN+EJGcPuuAw0BBhYs/+5Rj4wJBlkbu560I7SZ3X8tQKH/5Yg42z6pDqYE0MermxIsgaqO0kmorRgM28PSoWZQUmXQrvBl6s9CrAj9dYlXe23zEpHzz8kB0KUQL5N7mqNRHrJjXb8TwXrDkkXgO1+VBm7nMwhI7lpMpaxsh2nT5NdlU3bg1ZfzWo5nkXQ+zYSw255UWAe1Y4KsUYkjPZyHDnDMFTzhHXyPMi9nvI+JyM8EJCtaEAbxFgNiL+XcKHbc1pYxkePrnW4j3Gm
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mssql
      namespace: prod-tour-of-heroes
    type: Opaque

