apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mssql
  namespace: default
spec:
  encryptedData:
    SA_PASSWORD: AgCV0mgcNPBdjlW2s/OHFbV1n1mGFawpBkgz9wpxtcvzu/TAOAm/tQae2BpIThs1H4l54t/OtIagctQqKv/0gRVTJESev7KWcrLk8sDjTG3VoIz+6I2kaIRMHFtAnevqxH+pdADSc9p47dltrddoe6L4ITD0QfFiUbFm5jZTUsEtm7u4helv42r76G2354yKYBdTVh3otGoyk0CPPUE63WfLSS+EDi27KfJDF1LbCp0IoymzkBlMrurEVd67Hv1IkQvjBOtUCGmOitdAKUgbQAsCL6ZVsefxS7kgCWyx2sEwe6S6NKjZRn/olYpBZBZnNTYtiV3YE2eVfjLcejiQ0BnPesMCvblleDwRLGfClM2AGkPAML1ih4gD60tdfxN4OcDVog9lat+J/scbMPLyl/CPtyDkePycftVe89ppSZ/+4peTMIrSc4ylzgLQaIlLiro96ds7nykZQ9eUx57OOaiwjhuqqnKvUutW9mdlKT2pDjmaINXtIicpdzWwGDpXzXrvmRRhetaELwZXOZ134YE+Vi+/mlC1QlWgJANiwvLBFfc/jBZQ0Dd/zT5Ys5hUnuqtDyL2cMGg4HJFNVNEU5A/ZAIFWKsE82lEvmU9tDwtUsSnHmieSVavn6NLxO/asyYMHZYRmhQ6y+85HbSCDfaXG4UAbIZEQhBC99MIAJIV+m9BpnmhlAJh5lZjotDg3HsEQIyARGqY4fo6W2IDRRp4uMjp
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mssql
      namespace: default
    type: Opaque

