apiVersion: v1
kind: Secret
metadata:
    name: mssql
type: Opaque
stringData:
    SA_PASSWORD: ENC[AES256_GCM,data:ytJUQmoygFQ+pKc+UK/pAHALbA==,iv:L/DZaZmfYm7bhCSB7vCSDEFwG7+Faz/4hwwIWK5LiMo=,tag:AxqYl0lkFtG4PBhKFrD1mA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-19T15:59:50Z"
    mac: ENC[AES256_GCM,data:r7EogpYHcWix15ya56FOQWkkWn0mFvQlmuj6s+eTLDOMj8YwodQLZ5huDcdRrgHQyWTi6XOAskZ+ZESkLKn6Tl26WTkEKtiUbFqNfbA6Z7dU19ivq/c1DoLHuGk85XKdyVOJ2UgdKXnuTI0YShZ42qDP+KfDoMORUfkXECYkEMQ=,iv:WBUndz5gGd2PpolA/HoN8iYN+v3p5pgBn71pounlrOI=,tag:D+f3fdntLyx6KKSmXBy4Fg==,type:str]
    pgp:
        - created_at: "2022-04-19T15:59:50Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9YE9b+MZ3xCAQ//ZyJU4No8skbbFteM5gXd5bqu0PX3psPhH0ZfIx0V+xNX
            fBoZbxVI5pmfYAlJGVF1TjghPECQgpBhg4Zn7IypPQFgnBya8TBzEozYzswCrnGb
            GmRj9nfe9p8aVVIsQQfh35hAhy5frkVViSoz40qieSiiPAfLRY7dwafh11bz6dha
            O+F2R7wUNwBqR4NkNGSFF61IJKtn0iZSiZsjLCjRP9S0wgDtRK/x3q043eXByzyM
            rfYQlgekAowK4XtyhVNPZijq4fmiWRGZspe0ZAGdW9rAB9yGPCGdZ75tc9d8E07b
            MgVXY8fQnF+6jwf75Rn5y4mVXmVkTqvHtebXbD4Zvl461BkjyZ7M5MRYQfXU4uiu
            iqSZr4t2ldUZtn0mKFITN8Dkv4bDrLDyfXIPoxCfGE/Vi6J2varXm4K5OCFEstX0
            ACq7pRogJT7IxXb3En7w8k2HObLi74ixMMHU5PCk0wZUQqOoredcI1Xbfeu+RRHk
            8gEeMXC4bQtKCvCNnO7dRqTzOEGvGvTtq7X0lAXe+rpEX2AYX16/2J/qVX+knhtD
            6O0/yTpE4KSKtkpCMFSMPWHG4wy/+Myje3DqfqVhuB90T/QNTsxhrcqgqW8WUja/
            VXpRjTqR9he4JPclnMNFeZsUNeeTX25u2l6nCRyFgxPneaYkq0fE6D0w+sCPv1/U
            aAEJAhBgIFmzJS9BbJJsmWCcfLqA6L5iCIjCO48aioUYpV4znULx7Hk2psS7xdVI
            DfGQjiqEQ7zmR/i/6JWQ/rZWxDCYIuYSB7KjhZJxKgoZ0mfREonRFhFChYR9RIkx
            6yHSfGjXwfjt
            =VvTx
            -----END PGP MESSAGE-----
          fp: FE72F1D7FAA1B9CE6B1DA8E3DD7542BD4614B58D
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
