apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mssql
  namespace: default
spec:
  encryptedData:
    SA_PASSWORD: AgCqIim/+FZ1Xp4UbZq72RjbqBbTuIcnW+f8TYkA3SJY2O1zEQeIkrdiJBuR+mnIysqSszVvN0hxSR+opM81sGBs61ypLH/IEHRmHnb6zg65VAa5n0UipKh+c6WWd4MBhCcdYEd0cPGOhLegfg1X3F+oU9RW3TTrmTqWrUVptRjtqiJKY01wiSg5ImxROkn4Vj47a3FVR+Il2I49++sLykzDtD5D529tbZwSyhaAXKpCWr+BEITjXT3aAZc5p2V61h2B1swrmozO5dyjWwFydJRyBH7kaP5VNFfx5v47YGD3mf22gAW2FBgQEwTPGUBCSIUTyEq7bo9HrQtVq6X9BFXAy2fS1IpK1Xc+UG7T1ciZFihujun0CMXruLxuGKiAj0MPXgxLe0g6PCvDn/Fj8OHfC9WoRcI8MS+W60KULYg0vYe1pOqq3iqGZEHgG51+Su179pLB6dgWAIAGW11paL9iLFHYF8rwahxKdst4P3ThBX98Y/b96kSGmpGJSNoMnaftn3V8awTDZxsDqUIBpf48q07ZmypvowwWqVaOFiAePV/0s5wuVX/ennhm73/N/pDYldgZLfs0RceuKx9sXKfEijjVHCk7zROWFXaQzYCDSINjaxfj3DlTdYCFrWs7wQfsk2lo9MMYIWVLodTpAb6Hel15Brg3DOWLSgfZm/2+H/zQEGSKd2FShJ/z10snvJA6MZ0PLFtJ875JMl+vK2gHkbtH
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mssql
      namespace: default
    type: Opaque

