apiVersion: v1
kind: Secret
metadata:
    name: sqlserver-connection-string
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:INk2rVZA1p32GAbobX0XH/QMrjanhJC8/CYicPe4Ow7yZOxV2O4Kme37qSdstbFGTDk153Y8/PZM+G3jKcCzKgI1zGHw4uQXg1jQJE8ZR5EAvr/BDkoxA7TZmgbn5XpYOnJh0b3pgEbeima2ydjGdWsnI69J2iKaXF4gdTV3Ug==,iv:qwhaLbrUgogj7l1Lt1fAJfg0iec9DRC4QbVGVA4qeEI=,tag:56TPZz6gEwQRS+Qbmt654Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-19T16:45:09Z"
    mac: ENC[AES256_GCM,data:onzQyF+J5tbnFLNhgVa9j9LkRRxQ+31DaZ/sGneIrPA/Yg+G3+JK7tr5SCNNdMaMoCBzJvQyAxQe0mA5Daf+4Nj1+j9wqilOX+Coh8uKJa0TerPYEeek6iCHZBHYN3uydjKlWilrbOv0Tzfmna+A3RXpMC4Uf4nhsE9WCtmp3Ck=,iv:8fQnv3YXdFpxX6VTRZp46Wue7ecwmyrRi6zbyZ1yxK8=,tag:gtxuV5YLRYMe2WbMwXhEhA==,type:str]
    pgp:
        - created_at: "2022-04-19T16:45:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9YE9b+MZ3xCAQ/7BE5r5Bswx5N8n6PihB2D74gsD75arrekXfzJAJz3L/ZP
            8qjfiWvxWYl0TXL8hozn9uZocpOkiHtSyOJ+KbGOLXgF3paqepN63TVFxEe2wemF
            UW9AWYyE8X3uNjUZKK6kWuYx8lPrGcIB0sJnmClDKv3S67Eks7pZ3JOrUMjMaSJ7
            Fhp1qolHYwr9y2SfdpsK5S5nU4v6UXWc8xkpkXVJNnoTO6cUTLnYsWsM8JXGiXZl
            sqGQTzLGtOJ0inxnfDY5I0eiVMQOJHKOpFxgJ+OzuTCwsMmDzTqdklFaMSgL+4n1
            u6O/chIgU+/r304qlU1NBkLYV3IVi8jy3INLAu7+/dSNrCGeNakFQJ4WkpPOet4Y
            lxcln/i12FZOb2Wcwd4V3yfY3EQA7AVlMLdvlTnIWi/VjySBKH7TdX0+5t0ISc2x
            TLJuUuJnaFiHh7lFpBugrlavdIMZL0tuntOw+Q8zxvZDlYRg34BVR6Aq8mr9Fucm
            5rLjJyGGbwRCB3lRjuZ3YeJGBseQ61nIwawCBkb0DiMxVz/UnAQXuMeSxLWo75b4
            SnBIzj/wVlzDuMZSVQe0MwYWKGN8dMbEyvpXevOGqJelCuwdGb3aBRRJqmjT9LWe
            6JiZg70bebZVjFjWc3vNY6c7+3XosyYYLU7Fw+btIhcEtTAhZNst5RJdGySgHevU
            aAEJAhDKqYwRVSlHs/WFV/bggEAe6naCKey/U/OZzuj/28ArUEHCHcjNYA4VmPuT
            dcU5JKVUEACuZPxvSO+Ad48xuTEdILcfYTy1MkL+rpHHwpGdxsd9ySPbUNntUVhJ
            KPASanmRLORC
            =3/Aw
            -----END PGP MESSAGE-----
          fp: FE72F1D7FAA1B9CE6B1DA8E3DD7542BD4614B58D
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
